/** Garage screen kit: the session list, the personal bests and the demo bay. */
export { mountAdvice } from './advice';
export type { MountAdvice, MountConcern } from './advice';
export { MountNotice } from './MountNotice';
export { personalBests, bestGradeOf, lastRunStanding, trackKeyOf, UNTRACKED } from './bests';
export type { BestRecord, LastRunStanding, RecordKey, TrackBests } from './bests';
export { angleText, pointsText, rowFootnote, slidesText } from './labels';
export type { Slot } from './labels';
export { forgetDetails, readDetail } from './lastRun';
export type { LastRunDetail } from './lastRun';
export { DEMO_SETS, DEMO_NAMES, clearDemoSessions, demoSetPresent, resolveDemoRequest, seedDemoRun, seedDemoSessions } from './demo';
export type { DemoRun, SeedProgress } from './demo';
export { useGarage } from './useGarage';
export type { Garage, GarageFault } from './useGarage';
export { gradeStateOf, gradeStateColor } from './grade';
export type { GradeState } from './grade';
export { GradeBadge } from './GradeBadge';
export type { GradeBadgeProps } from './GradeBadge';
export { TRACE_CEILING_DEG } from './trace';
export { LastRunCard, RunRow } from './SessionCards';
export { BestsBoard } from './BestsBoard';
export { EmptyGarage } from './EmptyGarage';
export { DriveSlab } from './DriveSlab';
export { SimBay, MOUNT_LEVELS } from './SimBay';
export { SwipeToDelete } from './SwipeToDelete';
export { ConfirmDialog } from './ConfirmDialog';
