/**
 * GENERATED by `npx tsx tools/audio/bench.ts emit=1` — do not edit by hand.
 *
 * The sequences the `/sound` lab replays, FOUND in real runs through the real pipeline and
 * the real mixer. Each one carries the command that reproduces it and the second of that run
 * it happened at, because the lab used to state three timings that its own cited command did
 * not produce — including a spin on a run that has none.
 */
import type { SoundId } from './bank';

export interface SoundSequence {
  key: string;
  label: string;
  /** The command that reproduces the run this was measured on. Empty when constructed. */
  command: string;
  /** Recording second of that run, or null for a constructed demonstration. */
  atS: number | null;
  note: string;
  steps: ReadonlyArray<{ id: SoundId; atS: number }>;
}

export const SOUND_SEQUENCES: readonly SoundSequence[] = [
  {
    key: "flick",
    label: "The flick",
    command: "npx tsx tools/audio/bench.ts harbor 1 2",
    atS: 42.01,
    note: "at 42.01 s: the whip on the phase edge, MANJI 413 ms later where the callout lands, gold at 751 ms",
    steps: [{ id: "transition", atS: 0 }, { id: "manji", atS: 0.413 }, { id: "extreme", atS: 0.751 }],
  },
  {
    key: "lost",
    label: "The spin",
    command: "npx tsx tools/audio/bench.ts touge 10 2",
    atS: 73.94,
    note: "at 73.94 s: CHAIN LOST and SPIN fire on the SAME frame — the cause outranks the consequence, so you hear one",
    steps: [{ id: "lost", atS: 0 }, { id: "spin", atS: 0 }],
  },
  {
    key: "mud",
    label: "Three at once",
    command: "",
    atS: null,
    note: "constructed, not measured: three cues inside 150 ms against two voices — read the decisions below",
    steps: [{ id: "long", atS: 0 }, { id: "lap", atS: 0.07 }, { id: "spin", atS: 0.14 }],
  },
];
